### PR TITLE
enhance navbar

### LINKED ISSUE #3: Navbar Styling Enhancement
The Navbar component could use some improvements in terms of styling. Add hover effects or adjust the layout to make it more visually appealing.

### PR DESCRIPTION
**Pull request by Achal-00**
#### Reference Issues / PRs

closes #3

#### What does this implement/fix?

Improve the navbar component and add responsiveness

https://github.com/abhideepkumar/sigmaevents/assets/106076516/d727aece-b850-44a8-a823-385836ef5cac

https://github.com/abhideepkumar/sigmaevents/assets/106076516/dbc17bff-47a1-4804-8849-6364cf436936

#### Any other comments?

No

### CODE REVIEW

**Comment by abhideepkumar** [comment]
Add some more changes:
Take out the Login button from the hamburger menu to the navbar in the mobile view and If It's logged in then instead of setting word, put an icon of Profile-edit.

**Comment by Achal-00** [comment]
In the navigation bar, where should I place the login button?

**Comment by abhideepkumar** [comment]
> In the navigation bar, where should I place the login button?

at the left end keep the logo there and at right end keep Login and then the Button

**Comment by Achal-00** [comment]
### updated navbar

mob

mobile-log

desk-log

**Pull request merged**
